# Generated by Django 3.2 on 2021-12-25 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserOAuth',
        ),
    ]
