# Generated by Django 3.2 on 2021-12-19 10:42

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='关于标题')),
                ('body', mdeditor.fields.MDTextField(verbose_name='内容')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '关于页',
                'verbose_name_plural': '关于页',
            },
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.URLField(verbose_name='轮播图')),
                ('url', models.URLField(verbose_name='链接地址')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='图片标题')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
            ],
            options={
                'verbose_name': '轮播图管理',
                'verbose_name_plural': '轮播图管理',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=10, verbose_name='职位')),
                ('company', models.CharField(max_length=20, verbose_name='单位')),
                ('location', models.CharField(max_length=10, verbose_name='地址')),
                ('email', models.EmailField(max_length=50, verbose_name='邮箱')),
                ('github', models.URLField(verbose_name='GitHub')),
                ('gitee', models.URLField(verbose_name='码云')),
                ('qq', models.CharField(max_length=15, verbose_name='QQ')),
                ('qq_img', models.URLField(verbose_name='QQ二维码')),
                ('wechat', models.CharField(max_length=20, verbose_name='微信')),
                ('wechat_img', models.URLField(verbose_name='微信二维码')),
                ('wechat_pay', models.URLField(verbose_name='微信收款码')),
                ('ali_pay', models.URLField(verbose_name='支付宝收款码')),
            ],
            options={
                'verbose_name': '博主信息',
                'verbose_name_plural': '博主信息',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='网站名称')),
                ('logo', models.URLField(verbose_name='网站logo')),
                ('url', models.URLField(verbose_name='网址')),
                ('describe', models.CharField(blank=True, max_length=100, null=True, verbose_name='站点简介')),
                ('type', models.CharField(choices=[('1', '友情链接'), ('2', '强烈推荐')], default=1, max_length=1, verbose_name='类型')),
                ('is_activate', models.BooleanField(default=False, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '友情链接',
                'verbose_name_plural': '友情链接',
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.URLField(default='https://oss.cuiliangblog.cn/images/logo.png', verbose_name='网站logo')),
                ('icon', models.URLField(default='https://oss.cuiliangblog.cn/image/favicon.ico', verbose_name='icon图标')),
                ('name', models.CharField(max_length=20, verbose_name='网站名称')),
                ('domain', models.URLField(verbose_name='网站域名')),
                ('title', models.CharField(max_length=50, verbose_name='首页标题')),
                ('keywords', models.CharField(blank=True, max_length=200, null=True, verbose_name='META关键词')),
                ('describe', models.CharField(blank=True, max_length=300, null=True, verbose_name='META描述')),
                ('copyright', models.CharField(max_length=100, verbose_name='版权信息')),
                ('icp_num', models.CharField(blank=True, max_length=100, null=True, verbose_name='ICP备案号')),
                ('icp_url', models.URLField(blank=True, null=True, verbose_name='ICP备案链接')),
                ('police_num', models.CharField(blank=True, max_length=100, null=True, verbose_name='公安备案号')),
                ('police_url', models.URLField(blank=True, null=True, verbose_name='公安备案链接')),
                ('photo', models.URLField(default='https://oss.cuiliangblog.cn/images/photo.jpg', verbose_name='默认头像')),
                ('cover', models.URLField(default='https://oss.cuiliangblog.cn/image/cover.jpg', verbose_name='默认封面')),
            ],
            options={
                'verbose_name': '网站配置',
                'verbose_name_plural': '网站配置',
            },
        ),
    ]
