# Generated by Django 3.2 on 2022-02-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='type',
            field=models.CharField(choices=[('1', '友情链接'), ('2', '强烈推荐')], default='1', max_length=1, verbose_name='类型'),
        ),
    ]
