# Generated by Django 3.2 on 2022-05-16 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_link_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='sitemap',
            field=models.URLField(blank=True, null=True, verbose_name='网站地图链接'),
        ),
    ]
