# Generated by Django 3.2 on 2022-09-03 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_siteconfig_sitemap'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='rss',
            field=models.URLField(default=1, verbose_name='RSS订阅地址'),
            preserve_default=False,
        ),
    ]
