# Generated by Django 3.2 on 2022-09-03 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_siteconfig_rss'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='vx_public',
            field=models.URLField(default=1, verbose_name='微信公众号二维码'),
            preserve_default=False,
        ),
    ]
