# Generated by Django 3.2 on 2022-09-03 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_info_vx_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfig',
            name='rss',
        ),
        migrations.AddField(
            model_name='info',
            name='rss',
            field=models.URLField(default=1, verbose_name='RSS订阅地址'),
            preserve_default=False,
        ),
    ]
