# Generated by Django 3.2 on 2021-12-19 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='文章分类')),
            ],
            options={
                'verbose_name': '文章分类',
                'verbose_name_plural': '文章分类',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='笔记名称')),
                ('cover', models.URLField(default='https://oss.cuiliangblog.cn/images/cover.jpg', verbose_name='笔记封面')),
            ],
            options={
                'verbose_name': '笔记名称',
                'verbose_name_plural': '笔记名称',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='文章标签')),
            ],
            options={
                'verbose_name': '文章标签',
                'verbose_name_plural': '文章标签',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='笔记标题')),
                ('body', mdeditor.fields.MDTextField()),
                ('view', models.PositiveIntegerField(default=0, verbose_name='阅读量')),
                ('like', models.PositiveIntegerField(default=0, verbose_name='点赞数')),
                ('collect', models.PositiveIntegerField(default=0, verbose_name='收藏数')),
                ('comment', models.PositiveIntegerField(default=0, verbose_name='评论数')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_release', models.BooleanField(default=True, verbose_name='是否发布')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.note', verbose_name='所属笔记')),
            ],
            options={
                'verbose_name': '笔记内容',
                'verbose_name_plural': '笔记内容',
            },
        ),
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='标题名称')),
                ('order', models.IntegerField(default=1, verbose_name='序号')),
                ('level', models.IntegerField(default=2, verbose_name='等级')),
                ('father', models.IntegerField(blank=True, null=True, verbose_name='父目录ID')),
                ('note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.note', verbose_name='笔记名称')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.section', verbose_name='笔记内容')),
            ],
            options={
                'verbose_name': '笔记目录',
                'verbose_name_plural': '笔记目录',
                'ordering': ('father', 'order'),
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('abstract', models.TextField(blank=True, max_length=200, verbose_name='摘要')),
                ('cover', models.URLField(default='https://oss.cuiliangblog.cn/images/cover.jpg', verbose_name='文章封面')),
                ('body', mdeditor.fields.MDTextField()),
                ('view', models.PositiveIntegerField(default=0, verbose_name='阅读量')),
                ('like', models.PositiveIntegerField(default=0, verbose_name='点赞数')),
                ('collect', models.PositiveIntegerField(default=0, verbose_name='收藏数')),
                ('comment', models.PositiveIntegerField(default=0, verbose_name='评论数')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_recommend', models.BooleanField(default=False, verbose_name='是否推荐显示')),
                ('is_release', models.BooleanField(default=True, verbose_name='是否发布')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.category', verbose_name='分类')),
                ('tags', models.ManyToManyField(blank=True, to='blog.Tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '文章内容',
                'verbose_name_plural': '文章内容',
                'ordering': ('-created_time',),
            },
        ),
    ]
