# Generated by Django 3.2 on 2022-03-05 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='level',
            field=models.IntegerField(default=1, verbose_name='等级'),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='note',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.note', verbose_name='笔记名称'),
            preserve_default=False,
        ),
    ]
