# Generated by Django 3.2 on 2022-03-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_catalogue_options'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['title', 'category', 'created_time'], name='blog_articl_title_12b0b3_idx'),
        ),
    ]
