# Generated by Django 3.2 on 2022-03-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_blog_articl_title_12b0b3_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['title', 'note', 'created_time'], name='blog_sectio_title_2d7f6a_idx'),
        ),
    ]
