# Generated by Django 3.2 on 2022-09-11 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_note_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='document_count',
            new_name='items_count',
        ),
    ]
