# Generated by Django 3.2 on 2022-09-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_rename_document_count_note_items_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'verbose_name': '笔记列表 ', 'verbose_name_plural': '笔记列表 '},
        ),
        migrations.RemoveField(
            model_name='section',
            name='is_release',
        ),
        migrations.AddField(
            model_name='section',
            name='slug',
            field=models.CharField(default=1, max_length=50, verbose_name='标识ID'),
            preserve_default=False,
        ),
    ]
