# Generated by Django 3.2 on 2022-09-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_section_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogue',
            name='father',
        ),
        migrations.AlterField(
            model_name='section',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
