# Generated by Django 3.2 on 2022-09-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20220911_1911'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogue',
            options={'verbose_name': '笔记目录', 'verbose_name_plural': '笔记目录'},
        ),
        migrations.RemoveField(
            model_name='catalogue',
            name='level',
        ),
        migrations.RemoveField(
            model_name='catalogue',
            name='name',
        ),
        migrations.RemoveField(
            model_name='catalogue',
            name='order',
        ),
        migrations.RemoveField(
            model_name='catalogue',
            name='section',
        ),
        migrations.AddField(
            model_name='catalogue',
            name='catalogue',
            field=models.JSONField(default=1, verbose_name='目录'),
            preserve_default=False,
        ),
    ]
