# Generated by Django 3.2 on 2022-09-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20220911_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
