# Generated by Django 4.2.2 on 2025-07-24 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemoProvince',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='名称')),
                ('code', models.CharField(max_length=30, verbose_name='编码')),
            ],
            options={
                'verbose_name': '示例省份',
                'verbose_name_plural': '示例省份',
            },
        ),
        migrations.CreateModel(
            name='DemoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('sex', models.CharField(choices=[('1', '男'), ('2', '女')], default='1', max_length=1, verbose_name='性别')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('height', models.IntegerField(default=175, verbose_name='身高(cm)')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='体重(kg)')),
                ('photo', models.URLField(blank=True, null=True, verbose_name='头像')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('introduction', models.TextField(blank=True, null=True, verbose_name='个人介绍')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.demoprovince', verbose_name='省份')),
            ],
            options={
                'verbose_name': '示例用户',
                'verbose_name_plural': '示例用户',
            },
        ),
    ]
