# Generated by Django 3.2 on 2021-12-21 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadImg',
        ),
    ]
